export const FACTORY_MARK = 'FACTORY_MARK';
export const FIXTURE_MARK = 'FIXTURE_MARK';
export const MARK_VALUE = '1';

export const CLASS_IDENTIFIER = 'CLASS_IDENTIFIER';
export const CLASS_DEPENDENCIES = 'CLASS_DEPENDENCIES';
export const FIXTURE_TX_LEVEL = 'ISOLATION_LEVEL';

export const FACTORY_TARGET = 'FACTORY_TARGET';
export const FACTORY_NAME = 'FACTORY_NAME';
export const DEFAULT_FACTORY_NAME = 'default';
