name: Test

on:
  push:
    branches:
    - '**'

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Install yarn packages
      run: yarn install
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test:coverage
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: './src/coverage/lcov.info'
        github-token: ${{ secrets.GITHUB_TOKEN }}
